version: 2

sources:
  - name: raw
    description: "Raw attendance data ingested into Snowflake"
    schema: raw

    tables:
      - name: raw_attendance
        description: "Raw student attendance records"
        config:                  
          loaded_at_field: loaded_at
          freshness:
            warn_after:
              count: 1
              period: day
            error_after:
              count: 2
              period: day

        columns:
          - name: student_id
            tests:
              - not_null
          
          - name: attendance_date
            tests:
              - not_null

          - name: loaded_at
            tests:
              - not_null
