version: 2

sources:
  - name: raw
    description: "Raw attendance data ingested into Snowflake"
    schema: raw

    tables:
      - name: raw_attendance
        description: "Raw student attendance records"
        loaded_at_field: attendance_date
        
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 5
            period: day
        
        columns:
          - name: student_id
            tests:
              - not_null
          
          - name: attendance_date
            tests:
              - not_null
